version: "3.7"

services:
  ism-mysql-db:
    image: mysql:latest
    container_name: ism-mysql-db
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ism12345678900
      - MYSQL_DATABASE=ism-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=ism12345678900
    command:
      - --character-set-server=utf8mb4
    volumes:
      - ism-mysql-volume:/var/lib/mysql

  ism-api-server:
    build:
      context: ./server
      target: ism-srv-development
    container_name: ism-api-server
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - ism-mysql-db
    volumes:
      - ./server/src:/app/src
    env_file:
      - .env
    environment:
      - SYNC_DATA

  ism-redis:
    image: redis:6.0.5
    container_name: ism-redis
    ports:
      - "6379:6379"
    restart: always
    entrypoint:
      - "redis-server"
      - "--notify-keyspace-events AKE"

volumes:
  ism-mysql-volume:
